/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f3f0f1",
        "secondary": "#505f76",
        "tertiary-fixed-dim": "#dcc2a4",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#303031",
        "surface-container-highest": "#e5e2e3",
        "error-container": "#ffdad6",
        "surface-container-high": "#eae7e9",
        "on-secondary-fixed-variant": "#38485d",
        "on-tertiary-fixed": "#261906",
        "secondary-container": "#d0e1fb",
        "on-secondary-container": "#54647a",
        "outline-variant": "#c6c6cd",
        "tertiary-container": "#261906",
        "surface-container-low": "#f6f3f4",
        "on-primary-fixed-variant": "#404758",
        "surface-tint": "#575e70",
        "on-primary-fixed": "#141b2b",
        "background": "#fcf8fa",
        "surface": "#fcf8fa",
        "on-background": "#1b1b1d",
        "on-primary-container": "#7d8497",
        "on-surface-variant": "#45464c",
        "secondary-fixed": "#d3e4fe",
        "primary-fixed-dim": "#c0c6db",
        "on-tertiary-fixed-variant": "#55442d",
        "on-tertiary-container": "#968065",
        "on-secondary-fixed": "#0b1c30",
        "tertiary-fixed": "#f9debf",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-variant": "#e5e2e3",
        "surface-bright": "#fcf8fa",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dce2f7",
        "inverse-primary": "#c0c6db",
        "primary": "#000000",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "surface-container": "#f0edee",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-surface": "#1b1b1d",
        "primary-container": "#141b2b",
        "surface-dim": "#dcd9db",
        "outline": "#76777d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-page": "32px",
        "stack-md": "16px",
        "unit": "4px",
        "gutter": "24px",
        "container-max": "1440px",
        "stack-sm": "8px",
        "card-padding": "24px",
        "stack-lg": "32px"
      },
    },
  },
  plugins: [],
}
